### ISSUE TITLE
Problem reading skymodel with no Patches

### ISSUE THREAD

**Issue by wllwen007** [darafferty/LSMTool#29]
I have an issue loading a simple patchless gsm skymodel in the latest release version:
```
import os
import lsmtool
os.system('wget -O tgts.skymodel "https://lcs165.lofar.eu/cgi-bin/gsmv1.cgi?coord=%f,%f&radius=%f&unit=deg"' % (169, 52, 6/2.)) 
lsm = lsmtool.load('tgts.skymodel')
```
This works in v1.4.5 but fails with the following error in v1.4.6
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-12832a968c1c>", line 11, in <module>
    lsm = lsmtool.load("tgts.skymodel")  # , beamMS=MSs.getListObj()[0])
  File "/usr/local/lib/python3.8/dist-packages/lsmtool/__init__.py", line 85, in load
    return SkyModel(fileName, beamMS=beamMS, VOPosition=VOPosition,
  File "/usr/local/lib/python3.8/dist-packages/lsmtool/skymodel.py", line 121, in __init__
    self.table = Table.read(fileName, format='makesourcedb')
  File "/usr/lib/python3/dist-packages/astropy/table/connect.py", line 52, in __call__
    out = registry.read(cls, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/astropy/io/registry.py", line 523, in read
    data = reader(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lsmtool/tableio.py", line 156, in skyModelReader
    table = createTable(outlines, metaDict, colNames, colDefaults)
  File "/usr/local/lib/python3.8/dist-packages/lsmtool/tableio.py", line 191, in createTable
    patchCol = 'col{0}'.format(colNames.index('Patch')+1)
ValueError: 'Patch' is not in list
```

both were using astropy v4.0

**Comment by darafferty** [comment]
Thanks for reporting this -- should be fixed now. I will make a new release and update it on PyPI.
